[package]
name = "Save_Manager_Injector"
author = "JJ"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1"
ureq = { version = "2", features = ["json"] }
tungstenite = "0.20"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
